# Generated by Django 4.1.7 on 2023-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='image',
        ),
        migrations.AddField(
            model_name='custuser',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='gender', max_length=100),
        ),
    ]
